before_commands:
    - "composer install --no-dev"

filter:
    excluded_paths: [vendor/*]

checks:
    php:
        code_rating: true
        duplication: true

tools:
    php_analyzer: true
    sensiolabs_security_checker: true
    php_mess_detector: true
    php_code_coverage: true
    php_cpd: true
    php_pdepend:
        excluded_dirs: [vendor]
    php_code_sniffer:
        extensions:
            - php
        filter:
            excluded_paths: [vendor/*]
        config:
            encoding: utf8
            standard: "PSR2"
